server:
  port: 80

spring:
  application:
    name: openfeign-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


eureka:

  #  instance:
  #    hostname: localhost #eureka服务端的实例名称
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/