server:
  port: 9527

eureka:
  instance:
    hostname: cloud-gateway-service #eureka服务端的实例名称
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
       - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
         uri: http://localhost:8001          #匹配后提供服务的路由地址
         predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

#        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
